name: CI - Selenium
on: [push]
jobs:
  selenium:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"
      - name: Install Dependencies
        run: |
          pip install selenium webdriver-manager
      - name: Run Selenium Test
        run: |
          cd codigo-testes/selenium
          python login_test.py
